# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf3551e5d9142ac352ee34adc9f65af2bc16bf8610921cbe22ded73127cf7e2f17d6f7385f4a6f889dc77d57a16dbc17735ad88cf840a142d9e7be7f940a4d3

test:
  secret_key_base: 7cf780803f1da9bacdb97347e2715ea7f7a53573539e056f62947e8ecaf65ff578cc1e45ce13990383bcad28be143da4f53ffbf8ba7c72ad7b94488a81a434bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
